# Generated by Django 5.2.5 on 2025-08-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='iglesias/'),
        ),
    ]
