# Generated by Django 5.2.5 on 2025-08-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_iglesia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='iglesia',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
