# Generated by Django 5.2.5 on 2025-08-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_remove_iglesia_imagen_iglesia_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='horariomisa',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='horarioMisa',
        ),
        migrations.RemoveField(
            model_name='iglesia',
            name='listaActividades',
        ),
        migrations.AddField(
            model_name='actividades',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='dia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariomisa',
            name='dia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horariomisa',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariomisa',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.iglesia'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
