# Generated by Django 5.2.5 on 2025-08-21 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_remove_noticia_categoria_remove_horariomisa_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.iglesia'),
        ),
    ]
