# Generated by Django 5.2.5 on 2025-08-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_actividades_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioIglesias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iglesias_admin', models.ManyToManyField(blank=True, related_name='administradores', to='sitio.iglesia')),
                ('iglesias_suscripto', models.ManyToManyField(blank=True, related_name='suscriptores', to='sitio.iglesia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_iglesias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
