# Generated by Django 5.2.5 on 2025-08-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_usuarioiglesias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='iglesia',
            name='contacto_secretaria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='iglesias/'),
        ),
    ]
