# Generated by Django 5.2.5 on 2025-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_remove_iglesia_imagen_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inicio/')),
            ],
        ),
    ]
