# Generated by Django 5.2.5 on 2025-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_noticia_delete_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
