# Generated by Django 5.2.5 on 2025-08-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_actividades_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='detalles',
        ),
        migrations.DeleteModel(
            name='HorarioMisa',
        ),
    ]
