# Generated by Django 5.2.5 on 2025-09-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_remove_actividades_detalles_delete_horariomisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fechaVencimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
