# Generated by Django 5.2.5 on 2025-09-17 19:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_iglesia_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 19, 15, 43, 645546, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 19, 15, 43, 645417, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='iglesiaAsociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.iglesia'),
        ),
    ]
