# Generated by Django 5.2.5 on 2025-09-18 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_noticia_estado_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 4, 54, 41, 545692, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 18, 4, 54, 41, 545632, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
