# Generated by Django 5.2.5 on 2025-09-18 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_alter_noticia_creador_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 5, 41, 48, 195006, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 18, 5, 41, 48, 194978, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
