# Generated by Django 5.2.5 on 2025-09-19 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_alter_noticia_estado_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 21, 33, 1, 591040, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 19, 21, 33, 1, 591013, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
