# Generated by Django 5.2.5 on 2025-09-20 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0027_noticia_motivo_rechazo_alter_noticia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 27, 6, 8, 15, 594037, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 6, 8, 15, 593583, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
