# Generated by Django 5.2.5 on 2025-09-21 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0029_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descripcion_editada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='en_revision_edicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_editada',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/edits/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo_editado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 1, 27, 33, 796083, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 1, 27, 33, 796033, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
