# Generated by Django 5.2.5 on 2025-09-21 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado_edicion',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_revision_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='motivo_rechazo_edicion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 28, 19, 42, 47, 604965, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 19, 42, 47, 604931, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
