# Generated by Django 5.2.5 on 2025-09-22 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0033_noticia_editor_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 4, 48, 30, 885314, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 4, 48, 30, 885283, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
