# Generated by Django 5.2.5 on 2025-09-22 16:30

import functools
import sitio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0034_alter_noticia_fechaaceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='ultima_edicion_aprobada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaAceptacion',
            field=models.DateTimeField(default=functools.partial(sitio.models.fecha_vencimiento, *(7,), **{}), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaVencimiento',
            field=models.DateTimeField(default=functools.partial(sitio.models.fecha_vencimiento, *(30,), **{}), null=True),
        ),
    ]
