# Generated by Django 5.2.5 on 2025-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0035_noticia_ultima_edicion_aprobada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo_editado',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
