# Generated by Django 5.2.5 on 2025-10-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0036_alter_noticia_titulo_alter_noticia_titulo_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipo',
            field=models.CharField(choices=[('permanente', 'Permanente'), ('especial', 'Especial')], default='permanente', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fechaVencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
